SET check_function_bodies = false;
INSERT INTO public.fuel (id, fossil, category, label_en, label_de, order_by) VALUES ('PETROL', true, 'LIQUID', 'Petrol', 'Ottokraftstoff', 42);
INSERT INTO public.fuel (id, fossil, category, label_en, label_de, order_by) VALUES ('DIESEL', true, 'LIQUID', 'Gasoil', 'Diesel', 42);
INSERT INTO public.fuel (id, fossil, category, label_en, label_de, order_by) VALUES ('BIODIESEL', false, 'LIQUID', 'Bio-Gasoil', 'Biodiesel', 42);
INSERT INTO public.fuel (id, fossil, category, label_en, label_de, order_by) VALUES ('LIGNITE', true, 'SOLID', 'Brown coal', 'Braunkohle', 42);
INSERT INTO public.fuel (id, fossil, category, label_en, label_de, order_by) VALUES ('LIGNITE_BRIQUETTE', true, 'SOLID', 'Brown coal briquette', 'Braunkohlenbrikett', 42);
INSERT INTO public.fuel (id, fossil, category, label_en, label_de, order_by) VALUES ('HARDCOAL', true, 'SOLID', 'Hard coal', 'Steinkohle', 42);
INSERT INTO public.fuel (id, fossil, category, label_en, label_de, order_by) VALUES ('HARDCOAL_COKE', true, 'SOLID', 'Hard coal coke', 'Steinkohlenkoks', 42);
INSERT INTO public.fuel (id, fossil, category, label_en, label_de, order_by) VALUES ('WOOD', false, 'SOLID', 'Wood', 'Holz', 42);
INSERT INTO public.fuel (id, fossil, category, label_en, label_de, order_by) VALUES ('NATURAL_GAS', true, 'GASEOUS', 'Natural gas', 'Erdgas', 42);
INSERT INTO public.product (id, label_en, label_de, order_by) VALUES ('BEER', 'Beer', 'Bier', 42);
INSERT INTO public.product (id, label_en, label_de, order_by) VALUES ('BREAD', 'Bread', 'Brot', 42);
INSERT INTO public.product (id, label_en, label_de, order_by) VALUES ('PIZZA', 'Pizza', 'Pizza', 42);
INSERT INTO public.product (id, label_en, label_de, order_by) VALUES ('NITRIC_ACID', 'Nitric acid', 'Salpetersäure', 42);
INSERT INTO public.product (id, label_en, label_de, order_by) VALUES ('LUBRICANT', 'Lubricant', 'Schmierstoff', 42);
INSERT INTO public.species (id, label_en, label_de, order_by) VALUES ('HUMAN', 'People', 'Mensch', 42);
INSERT INTO public.species (id, label_en, label_de, order_by) VALUES ('HORSE', 'Horse', 'Pferd', 42);
INSERT INTO public.species (id, label_en, label_de, order_by) VALUES ('PIG', 'Pig', 'Schwein', 42);
INSERT INTO public.species (id, label_en, label_de, order_by) VALUES ('DAIRY_COW', 'Dairy cow', 'Milchkuh', 42);
INSERT INTO public.species (id, label_en, label_de, order_by) VALUES ('MULE', 'Mule', 'Esel', 42);
INSERT INTO public.species (id, label_en, label_de, order_by) VALUES ('CAMEL', 'Camel', 'Kamel', 42);
INSERT INTO public.species (id, label_en, label_de, order_by) VALUES ('SHEEP', 'Sheep', 'Schaf', 42);
